# Generated by Django 3.1.4 on 2021-01-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала брони')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания брони')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Booking_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15, verbose_name='Статус')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Статус бронирования',
                'verbose_name_plural': 'Статусы бронирований',
            },
        ),
    ]
