# Generated by Django 3.2.4 on 2021-06-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='photo',
            field=models.ImageField(default='', upload_to='coworking/static/img/spaces-images'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='space',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
    ]
