# Generated by Django 3.2.4 on 2021-06-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='photo',
            field=models.ImageField(default='', upload_to='spaces-images'),
        ),
    ]
