# Generated by Django 3.2.4 on 2021-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_space_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='photo',
            field=models.ImageField(default='', upload_to='coworking/static/img/spaces-images'),
        ),
    ]
