# Generated by Django 3.2.4 on 2021-06-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_space_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='space',
        ),
        migrations.AddField(
            model_name='space',
            name='rating',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='spaces.rating'),
        ),
    ]
