# Generated by Django 3.2.4 on 2021-07-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210627_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, default='User', max_length=50, null=True, verbose_name='Роль'),
        ),
    ]
