# Generated by Django 3.1.4 on 2020-12-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=50, verbose_name='Email пользователя')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Телефон пользователя')),
            ],
        ),
    ]
