# Generated by Django 3.1.4 on 2020-12-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='user_id',
            new_name='user',
        ),
    ]
