# Generated by Django 3.1.4 on 2020-12-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=15, verbose_name='Тип пользователя')),
                ('access_level', models.IntegerField(verbose_name='Уровень доступа')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.user')),
            ],
        ),
    ]
